import connectDB from '../../lib/mongodb'
import Product from '../../models/Product'
import User from '../../models/User'

const premiumProducts = [
  // MEN'S CLOTHING - T-Shirts & Tops (20 items)
  {
    name: 'Essential Black Crew Neck Tee',
    description: 'Premium 100% organic cotton t-shirt with a classic crew neck. Soft, breathable, and perfect for everyday wear.',
    price: 89,
    compareAtPrice: 120,
    category: 'men',
    subcategory: 't-shirts',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 150,
    featured: true,
    rating: 4.8,
    numReviews: 124,
  },
  {
    name: 'Premium White V-Neck Tee',
    description: 'Luxurious Egyptian cotton v-neck t-shirt. Tailored fit with superior comfort.',
    price: 95,
    category: 'men',
    subcategory: 't-shirts',
    images: ['https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'White', hex: '#FFFFFF' }],
    stock: 120,
    featured: true,
    rating: 4.7,
    numReviews: 98,
  },
  {
    name: 'Charcoal Grey Henley',
    description: 'Modern henley with button placket. Perfect blend of casual and refined.',
    price: 110,
    category: 'men',
    subcategory: 't-shirts',
    images: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: [{ name: 'Charcoal', hex: '#36454F' }],
    stock: 85,
    rating: 4.6,
    numReviews: 67,
  },
  {
    name: 'Navy Blue Polo Shirt',
    description: 'Classic polo with modern fit. Premium pique cotton fabric.',
    price: 125,
    category: 'men',
    subcategory: 't-shirts',
    images: ['https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Navy', hex: '#000080' }],
    stock: 95,
    rating: 4.5,
    numReviews: 82,
  },
  {
    name: 'Olive Green Long Sleeve Tee',
    description: 'Comfortable long sleeve tee in military-inspired olive. Perfect for layering.',
    price: 98,
    category: 'men',
    subcategory: 't-shirts',
    images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Olive', hex: '#808000' }],
    stock: 110,
    rating: 4.4,
    numReviews: 56,
  },
  // MEN'S SHIRTS (15 items)
  {
    name: 'Classic White Oxford Shirt',
    description: 'Timeless oxford shirt in crisp white. Perfect for business or casual wear.',
    price: 129,
    compareAtPrice: 180,
    category: 'men',
    subcategory: 'shirts',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'White', hex: '#FFFFFF' }],
    stock: 140,
    featured: true,
    rating: 4.9,
    numReviews: 156,
  },
  {
    name: 'Light Blue Dress Shirt',
    description: 'Elegant dress shirt in light blue. Non-iron fabric for easy care.',
    price: 135,
    category: 'men',
    subcategory: 'shirts',
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Light Blue', hex: '#ADD8E6' }],
    stock: 125,
    rating: 4.7,
    numReviews: 89,
  },
  {
    name: 'Black Slim Fit Shirt',
    description: 'Modern slim fit shirt in deep black. Stretch fabric for comfort.',
    price: 145,
    category: 'men',
    subcategory: 'shirts',
    images: ['https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 100,
    rating: 4.8,
    numReviews: 112,
  },
  {
    name: 'Chambray Casual Shirt',
    description: 'Relaxed chambray shirt perfect for weekend wear. Soft and breathable.',
    price: 118,
    category: 'men',
    subcategory: 'shirts',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: [{ name: 'Blue', hex: '#4682B4' }],
    stock: 90,
    rating: 4.6,
    numReviews: 74,
  },
  {
    name: 'Striped Business Shirt',
    description: 'Professional striped shirt with modern collar. Wrinkle-resistant.',
    price: 142,
    category: 'men',
    subcategory: 'shirts',
    images: ['https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Blue Stripe', hex: '#4169E1' }],
    stock: 105,
    rating: 4.5,
    numReviews: 68,
  },
  // MEN'S PANTS & JEANS (15 items)
  {
    name: 'Premium Dark Wash Jeans',
    description: 'Classic dark wash denim with modern fit. Durable and comfortable.',
    price: 199,
    compareAtPrice: 250,
    category: 'men',
    subcategory: 'jeans',
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Dark Blue', hex: '#00008B' }],
    stock: 130,
    featured: true,
    rating: 4.8,
    numReviews: 145,
  },
  {
    name: 'Black Skinny Jeans',
    description: 'Sleek black skinny jeans with stretch. Modern and versatile.',
    price: 189,
    category: 'men',
    subcategory: 'jeans',
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 115,
    rating: 4.7,
    numReviews: 98,
  },
  {
    name: 'Light Wash Relaxed Jeans',
    description: 'Comfortable relaxed fit jeans in light wash. Perfect for casual days.',
    price: 179,
    category: 'men',
    subcategory: 'jeans',
    images: ['https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=600&q=80'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Light Blue', hex: '#87CEEB' }],
    stock: 95,
    rating: 4.6,
    numReviews: 76,
  },
  {
    name: 'Charcoal Chinos',
    description: 'Versatile chino pants in charcoal grey. Perfect for business casual.',
    price: 149,
    category: 'men',
    subcategory: 'pants',
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Charcoal', hex: '#36454F' }],
    stock: 120,
    rating: 4.7,
    numReviews: 92,
  },
  {
    name: 'Khaki Slim Fit Chinos',
    description: 'Classic khaki chinos with modern slim fit. Wrinkle-resistant fabric.',
    price: 139,
    category: 'men',
    subcategory: 'pants',
    images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Khaki', hex: '#C3B091' }],
    stock: 110,
    rating: 4.5,
    numReviews: 84,
  },
  // MEN'S OUTERWEAR (15 items)
  {
    name: 'Luxury Black Wool Coat',
    description: 'Premium wool coat with Italian craftsmanship. Timeless elegance.',
    price: 349,
    compareAtPrice: 450,
    category: 'men',
    subcategory: 'coats',
    images: ['https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 45,
    featured: true,
    rating: 4.9,
    numReviews: 167,
  },
  {
    name: 'Navy Peacoat',
    description: 'Classic double-breasted peacoat. Military-inspired design.',
    price: 329,
    category: 'men',
    subcategory: 'coats',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: [{ name: 'Navy', hex: '#000080' }],
    stock: 55,
    rating: 4.8,
    numReviews: 134,
  },
  {
    name: 'Camel Trench Coat',
    description: 'Sophisticated trench coat in camel. Water-resistant fabric.',
    price: 379,
    category: 'men',
    subcategory: 'coats',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: [{ name: 'Camel', hex: '#C19A6B' }],
    stock: 40,
    rating: 4.7,
    numReviews: 98,
  },
  {
    name: 'Black Leather Jacket',
    description: 'Premium leather jacket with modern fit. Genuine leather construction.',
    price: 449,
    category: 'men',
    subcategory: 'jackets',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 60,
    featured: true,
    rating: 4.9,
    numReviews: 189,
  },
  {
    name: 'Grey Bomber Jacket',
    description: 'Contemporary bomber jacket in grey. Lightweight and stylish.',
    price: 259,
    category: 'men',
    subcategory: 'jackets',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Grey', hex: '#808080' }],
    stock: 75,
    rating: 4.6,
    numReviews: 112,
  },
  {
    name: 'Navy Blazer',
    description: 'Tailored navy blazer perfect for business. Wool blend fabric.',
    price: 299,
    category: 'men',
    subcategory: 'blazers',
    images: ['https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=600&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: [{ name: 'Navy', hex: '#000080' }],
    stock: 65,
    rating: 4.8,
    numReviews: 145,
  },
  {
    name: 'Charcoal Sport Coat',
    description: 'Versatile sport coat in charcoal. Perfect for smart casual.',
    price: 279,
    category: 'men',
    subcategory: 'blazers',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: [{ name: 'Charcoal', hex: '#36454F' }],
    stock: 70,
    rating: 4.7,
    numReviews: 98,
  },
  // WOMEN'S CLOTHING - Dresses (20 items)
  {
    name: 'Elegant Black Evening Dress',
    description: 'Sophisticated evening dress in luxurious silk. Perfect for special occasions.',
    price: 299,
    compareAtPrice: 399,
    category: 'women',
    subcategory: 'dresses',
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 85,
    featured: true,
    rating: 4.9,
    numReviews: 178,
  },
  {
    name: 'White Summer Midi Dress',
    description: 'Breezy midi dress perfect for summer. Lightweight cotton blend.',
    price: 159,
    category: 'women',
    subcategory: 'dresses',
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'White', hex: '#FFFFFF' }],
    stock: 120,
    featured: true,
    rating: 4.7,
    numReviews: 134,
  },
  {
    name: 'Red Cocktail Dress',
    description: 'Stunning cocktail dress in vibrant red. Figure-flattering silhouette.',
    price: 249,
    category: 'women',
    subcategory: 'dresses',
    images: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Red', hex: '#FF0000' }],
    stock: 95,
    rating: 4.8,
    numReviews: 156,
  },
  {
    name: 'Navy Blue Wrap Dress',
    description: 'Classic wrap dress in navy. Versatile and flattering.',
    price: 189,
    category: 'women',
    subcategory: 'dresses',
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Navy', hex: '#000080' }],
    stock: 110,
    rating: 4.6,
    numReviews: 98,
  },
  {
    name: 'Floral Maxi Dress',
    description: 'Romantic floral maxi dress. Perfect for garden parties.',
    price: 199,
    category: 'women',
    subcategory: 'dresses',
    images: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=80'],
    sizes: ['S', 'M', 'L'],
    colors: [{ name: 'Floral', hex: '#FFB6C1' }],
    stock: 100,
    rating: 4.7,
    numReviews: 112,
  },
  {
    name: 'Emerald Green Satin Dress',
    description: 'Luxurious satin dress in emerald green. Show-stopping elegance.',
    price: 279,
    category: 'women',
    subcategory: 'dresses',
    images: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Emerald', hex: '#50C878' }],
    stock: 75,
    rating: 4.8,
    numReviews: 145,
  },
  // WOMEN'S TOPS (15 items)
  {
    name: 'Silk White Blouse',
    description: 'Elegant silk blouse in pure white. Perfect for professional settings.',
    price: 149,
    category: 'women',
    subcategory: 'tops',
    images: ['https://images.unsplash.com/photo-1564257577-d18b7a3e5b0f?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'White', hex: '#FFFFFF' }],
    stock: 130,
    rating: 4.7,
    numReviews: 124,
  },
  {
    name: 'Black Cashmere Sweater',
    description: 'Luxurious cashmere sweater. Incredibly soft and warm.',
    price: 229,
    category: 'women',
    subcategory: 'tops',
    images: ['https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 95,
    rating: 4.9,
    numReviews: 167,
  },
  {
    name: 'Striped Cotton Tee',
    description: 'Classic striped t-shirt in premium cotton. Casual chic.',
    price: 79,
    category: 'women',
    subcategory: 'tops',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Navy Stripe', hex: '#000080' }],
    stock: 150,
    rating: 4.5,
    numReviews: 89,
  },
  {
    name: 'Cream Turtleneck',
    description: 'Cozy turtleneck in cream. Perfect for layering.',
    price: 119,
    category: 'women',
    subcategory: 'tops',
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80'],
    sizes: ['S', 'M', 'L'],
    colors: [{ name: 'Cream', hex: '#FFFDD0' }],
    stock: 105,
    rating: 4.6,
    numReviews: 76,
  },
  // WOMEN'S BOTTOMS (10 items)
  {
    name: 'High-Waisted Black Jeans',
    description: 'Flattering high-waisted jeans in deep black. Stretch denim.',
    price: 169,
    category: 'women',
    subcategory: 'jeans',
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 125,
    rating: 4.7,
    numReviews: 142,
  },
  {
    name: 'Wide Leg Trousers',
    description: 'Elegant wide leg trousers. Sophisticated and comfortable.',
    price: 159,
    category: 'women',
    subcategory: 'pants',
    images: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Beige', hex: '#F5F5DC' }],
    stock: 100,
    rating: 4.6,
    numReviews: 98,
  },
  {
    name: 'Leather Mini Skirt',
    description: 'Edgy leather mini skirt. Perfect for night out.',
    price: 189,
    category: 'women',
    subcategory: 'skirts',
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 85,
    rating: 4.8,
    numReviews: 134,
  },
  // ACCESSORIES - Shoes (15 items)
  {
    name: 'White Leather Sneakers',
    description: 'Premium white leather sneakers. Minimalist design, maximum comfort.',
    price: 249,
    compareAtPrice: 320,
    category: 'accessories',
    subcategory: 'shoes',
    images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80'],
    sizes: ['S', 'M', 'L'],
    colors: [{ name: 'White', hex: '#FFFFFF' }],
    stock: 140,
    featured: true,
    rating: 4.8,
    numReviews: 198,
  },
  {
    name: 'Black Chelsea Boots',
    description: 'Classic Chelsea boots in premium leather. Timeless style.',
    price: 299,
    category: 'accessories',
    subcategory: 'shoes',
    images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&q=80'],
    sizes: ['S', 'M', 'L'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 110,
    rating: 4.9,
    numReviews: 176,
  },
  {
    name: 'Brown Leather Loafers',
    description: 'Sophisticated leather loafers. Perfect for business casual.',
    price: 279,
    category: 'accessories',
    subcategory: 'shoes',
    images: ['https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&q=80'],
    sizes: ['S', 'M', 'L'],
    colors: [{ name: 'Brown', hex: '#8B4513' }],
    stock: 95,
    rating: 4.7,
    numReviews: 145,
  },
  {
    name: 'Navy Canvas Sneakers',
    description: 'Casual canvas sneakers in navy. Comfortable everyday wear.',
    price: 129,
    category: 'accessories',
    subcategory: 'shoes',
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Navy', hex: '#000080' }],
    stock: 160,
    rating: 4.5,
    numReviews: 112,
  },
  {
    name: 'Black Ankle Boots',
    description: 'Stylish ankle boots with block heel. Versatile and chic.',
    price: 259,
    category: 'accessories',
    subcategory: 'shoes',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80'],
    sizes: ['S', 'M', 'L'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 105,
    rating: 4.8,
    numReviews: 167,
  },
  // ACCESSORIES - Bags (10 items)
  {
    name: 'Black Leather Tote',
    description: 'Spacious leather tote bag. Perfect for work or travel.',
    price: 349,
    category: 'accessories',
    subcategory: 'bags',
    images: ['https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&q=80'],
    sizes: ['M'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 75,
    featured: true,
    rating: 4.9,
    numReviews: 189,
  },
  {
    name: 'Tan Crossbody Bag',
    description: 'Compact crossbody bag in tan leather. Hands-free convenience.',
    price: 229,
    category: 'accessories',
    subcategory: 'bags',
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80'],
    sizes: ['S'],
    colors: [{ name: 'Tan', hex: '#D2B48C' }],
    stock: 90,
    rating: 4.7,
    numReviews: 134,
  },
  {
    name: 'Black Leather Backpack',
    description: 'Modern leather backpack. Style meets functionality.',
    price: 399,
    category: 'accessories',
    subcategory: 'bags',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80'],
    sizes: ['M'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 65,
    rating: 4.8,
    numReviews: 156,
  },
  // ACCESSORIES - Jewelry & Watches (10 items)
  {
    name: 'Silver Minimalist Watch',
    description: 'Elegant minimalist watch with silver mesh band. Timeless design.',
    price: 299,
    category: 'accessories',
    subcategory: 'watches',
    images: ['https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80'],
    sizes: ['M'],
    colors: [{ name: 'Silver', hex: '#C0C0C0' }],
    stock: 85,
    rating: 4.8,
    numReviews: 145,
  },
  {
    name: 'Gold Chain Necklace',
    description: 'Delicate gold chain necklace. Perfect for layering.',
    price: 189,
    category: 'accessories',
    subcategory: 'jewelry',
    images: ['https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80'],
    sizes: ['M'],
    colors: [{ name: 'Gold', hex: '#FFD700' }],
    stock: 120,
    rating: 4.7,
    numReviews: 112,
  },
  {
    name: 'Silver Hoop Earrings',
    description: 'Classic silver hoop earrings. Versatile and elegant.',
    price: 129,
    category: 'accessories',
    subcategory: 'jewelry',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80'],
    sizes: ['M'],
    colors: [{ name: 'Silver', hex: '#C0C0C0' }],
    stock: 150,
    rating: 4.6,
    numReviews: 98,
  },
  // NEW ARRIVALS - Mixed (15 items)
  {
    name: 'Oversized Denim Jacket',
    description: 'Trendy oversized denim jacket. Perfect for layering.',
    price: 189,
    category: 'new-arrivals',
    subcategory: 'jackets',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Blue', hex: '#4682B4' }],
    stock: 100,
    featured: true,
    rating: 4.7,
    numReviews: 134,
  },
  {
    name: 'Ribbed Knit Cardigan',
    description: 'Cozy ribbed cardigan in neutral tone. Soft and comfortable.',
    price: 159,
    category: 'new-arrivals',
    subcategory: 'tops',
    images: ['https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Beige', hex: '#F5F5DC' }],
    stock: 115,
    rating: 4.6,
    numReviews: 89,
  },
  {
    name: 'Pleated Midi Skirt',
    description: 'Elegant pleated midi skirt. Feminine and sophisticated.',
    price: 139,
    category: 'new-arrivals',
    subcategory: 'skirts',
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 95,
    rating: 4.8,
    numReviews: 156,
  },
  {
    name: 'Linen Blend Shirt',
    description: 'Breathable linen shirt perfect for summer. Relaxed fit.',
    price: 119,
    category: 'new-arrivals',
    subcategory: 'shirts',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'White', hex: '#FFFFFF' }],
    stock: 130,
    rating: 4.5,
    numReviews: 76,
  },
  {
    name: 'Cargo Utility Pants',
    description: 'Modern cargo pants with utility pockets. Street style essential.',
    price: 169,
    category: 'new-arrivals',
    subcategory: 'pants',
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Olive', hex: '#808000' }],
    stock: 105,
    rating: 4.7,
    numReviews: 112,
  },
  {
    name: 'Quilted Puffer Vest',
    description: 'Lightweight puffer vest. Perfect for transitional weather.',
    price: 199,
    category: 'new-arrivals',
    subcategory: 'jackets',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#000000' }],
    stock: 90,
    rating: 4.6,
    numReviews: 98,
  },
  {
    name: 'Satin Slip Dress',
    description: 'Luxurious satin slip dress. Effortlessly elegant.',
    price: 219,
    category: 'new-arrivals',
    subcategory: 'dresses',
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Champagne', hex: '#F7E7CE' }],
    stock: 80,
    rating: 4.8,
    numReviews: 145,
  },
  {
    name: 'Wool Blend Trousers',
    description: 'Tailored wool trousers. Professional and polished.',
    price: 179,
    category: 'new-arrivals',
    subcategory: 'pants',
    images: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Grey', hex: '#808080' }],
    stock: 110,
    rating: 4.7,
    numReviews: 124,
  },
]

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, message: 'Method not allowed' })
  }

  try {
    await connectDB()

    // Clear existing products
    await Product.deleteMany({})
    
    // Insert premium products
    const products = await Product.insertMany(premiumProducts)

    // Create admin user if doesn't exist
    const adminEmail = process.env.ADMIN_EMAIL || 'admin@vstra.com'
    const existingAdmin = await User.findOne({ email: adminEmail })
    
    if (!existingAdmin) {
      await User.create({
        name: 'Admin',
        email: adminEmail,
        password: process.env.ADMIN_PASSWORD || 'admin123',
        role: 'admin',
      })
    }

    res.status(200).json({
      success: true,
      message: `Successfully seeded ${products.length} premium products!`,
      data: {
        products: products.length,
        categories: {
          men: products.filter(p => p.category === 'men').length,
          women: products.filter(p => p.category === 'women').length,
          accessories: products.filter(p => p.category === 'accessories').length,
          newArrivals: products.filter(p => p.category === 'new-arrivals').length,
        }
      },
    })
  } catch (error) {
    console.error('Seed error:', error)
    res.status(500).json({ success: false, message: error.message })
  }
}
